-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color7 = '#152120'
local Color8 = '#21161f'
local Color11 = '#8b888f'
local Color12 = '#fce566'
local Color9 = '#24272d'
local Color6 = '#0a0e14'
local Color10 = '#444444'
local Color4 = '#e3cf65'
local Color5 = '#f7f1ff'
local Color2 = '#7bd88f'
local Color0 = '#696969'
local Color1 = '#af98e6'
local Color3 = '#fc618d'

highlight('Comment', nil, Color0, 'italic')
highlight('Constant', nil, Color1, nil)
highlight('Number', nil, Color1, nil)
highlight('Function', nil, Color2, nil)
highlight('Function', nil, Color2, nil)
highlight('Error', nil, nil, 'italic')
highlight('Keyword', nil, Color3, nil)
highlight('Conditional', nil, Color3, nil)
highlight('Repeat', nil, Color3, nil)
highlight('Operator', nil, Color3, nil)
highlight('Type', nil, Color3, nil)
highlight('String', nil, Color4, nil)
highlight('StatusLine', Color5, Color6, nil)
highlight('WildMenu', Color6, Color5, nil)
highlight('Pmenu', Color6, Color5, nil)
highlight('PmenuSel', Color5, Color6, nil)
highlight('PmenuThumb', Color6, Color5, nil)
highlight('DiffAdd', Color7, nil, nil)
highlight('DiffDelete', Color8, nil, nil)
highlight('Normal', Color6, Color5, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color6, nil, nil)
highlight('LineNr', nil, Color10, nil)
highlight('TabLine', Color6, Color11, nil)
highlight('TabLineSel', Color12, Color6, nil)
highlight('TabLineFill', Color6, Color11, nil)
highlight('TSPunctDelimiter', nil, Color5, nil)

link('TSRepeat', 'Repeat')
link('CursorLineNr', 'Identifier')
link('NonText', 'Comment')
link('Repeat', 'Conditional')
link('TSType', 'Type')
link('TSFuncMacro', 'Macro')
link('Whitespace', 'Comment')
link('TSKeyword', 'Keyword')
link('Operator', 'Keyword')
link('TSProperty', 'TSField')
link('TSString', 'String')
link('TSFunction', 'Function')
link('TSTagDelimiter', 'Type')
link('TSTag', 'MyTag')
link('TelescopeNormal', 'Normal')
link('TSComment', 'Comment')
link('TSOperator', 'Operator')
link('TSParameterReference', 'TSParameter')
link('TSNumber', 'Number')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSField', 'Constant')
link('TSConditional', 'Conditional')
link('TSParameter', 'Constant')
link('TSLabel', 'Type')
link('Conditional', 'Operator')
link('TSPunctBracket', 'MyTag')
link('Macro', 'Function')
link('Folded', 'Comment')
link('TSNamespace', 'TSType')
link('TSConstant', 'Constant')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSFloat', 'Number')
